# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWnd.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ttf2pcb(object):
    def setupUi(self, ttf2pcb):
        ttf2pcb.setObjectName("ttf2pcb")
        ttf2pcb.resize(600, 485)
        ttf2pcb.setMinimumSize(QtCore.QSize(530, 320))
        ttf2pcb.setMaximumSize(QtCore.QSize(1920, 1920))
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(10)
        ttf2pcb.setFont(font)
        ttf2pcb.setMouseTracking(False)
        ttf2pcb.setWindowOpacity(1.0)
        ttf2pcb.setIconSize(QtCore.QSize(32, 32))
        ttf2pcb.setDocumentMode(False)
        ttf2pcb.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainUI = QtWidgets.QWidget(ttf2pcb)
        self.mainUI.setObjectName("mainUI")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainUI)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QHBoxLayout()
        self.top.setSpacing(1)
        self.top.setObjectName("top")
        self.status = QtWidgets.QGroupBox(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.status)
        self.verticalLayout_6.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.o_fftFileName_current = QtWidgets.QLabel(self.status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_fftFileName_current.sizePolicy().hasHeightForWidth())
        self.o_fftFileName_current.setSizePolicy(sizePolicy)
        self.o_fftFileName_current.setObjectName("o_fftFileName_current")
        self.verticalLayout_6.addWidget(self.o_fftFileName_current)
        self.top.addWidget(self.status)
        self.fontFileChs = QtWidgets.QHBoxLayout()
        self.fontFileChs.setSpacing(1)
        self.fontFileChs.setObjectName("fontFileChs")
        self.groupBox_3 = QtWidgets.QGroupBox(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.i_fontfileName = QtWidgets.QLineEdit(self.groupBox_3)
        self.i_fontfileName.setText("")
        self.i_fontfileName.setObjectName("i_fontfileName")
        self.horizontalLayout_8.addWidget(self.i_fontfileName)
        self.action_cfmFontFile = QtWidgets.QPushButton(self.groupBox_3)
        self.action_cfmFontFile.setObjectName("action_cfmFontFile")
        self.horizontalLayout_8.addWidget(self.action_cfmFontFile)
        self.fontFileChs.addWidget(self.groupBox_3)
        self.top.addLayout(self.fontFileChs)
        self.verticalLayout.addLayout(self.top)
        self.filePath = QtWidgets.QGroupBox(self.mainUI)
        self.filePath.setFlat(False)
        self.filePath.setCheckable(False)
        self.filePath.setObjectName("filePath")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filePath)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.i_externSettings = QtWidgets.QLineEdit(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.i_externSettings.setFont(font)
        self.i_externSettings.setTabletTracking(True)
        self.i_externSettings.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.i_externSettings.setInputMask("")
        self.i_externSettings.setDragEnabled(True)
        self.i_externSettings.setClearButtonEnabled(True)
        self.i_externSettings.setObjectName("i_externSettings")
        self.verticalLayout_2.addWidget(self.i_externSettings)
        self.label_4 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.i_sourceText = QtWidgets.QPlainTextEdit(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i_sourceText.setFont(font)
        self.i_sourceText.setBackgroundVisible(False)
        self.i_sourceText.setCenterOnScroll(True)
        self.i_sourceText.setObjectName("i_sourceText")
        self.verticalLayout_2.addWidget(self.i_sourceText)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.setting_method = QtWidgets.QComboBox(self.filePath)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_method.sizePolicy().hasHeightForWidth())
        self.setting_method.setSizePolicy(sizePolicy)
        self.setting_method.setObjectName("setting_method")
        self.setting_method.addItem("")
        self.setting_method.addItem("")
        self.setting_method.addItem("")
        self.setting_method.addItem("")
        self.verticalLayout_5.addWidget(self.setting_method)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.setting_scale = QtWidgets.QDoubleSpinBox(self.filePath)
        self.setting_scale.setMinimum(0.05)
        self.setting_scale.setMaximum(200.0)
        self.setting_scale.setSingleStep(0.05)
        self.setting_scale.setProperty("value", 0.8)
        self.setting_scale.setObjectName("setting_scale")
        self.verticalLayout_7.addWidget(self.setting_scale)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.setting_precision = QtWidgets.QSpinBox(self.filePath)
        self.setting_precision.setPrefix("")
        self.setting_precision.setMinimum(5)
        self.setting_precision.setMaximum(50)
        self.setting_precision.setSingleStep(2)
        self.setting_precision.setProperty("value", 20)
        self.setting_precision.setObjectName("setting_precision")
        self.verticalLayout_8.addWidget(self.setting_precision)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.filePath)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.setting_space = QtWidgets.QDoubleSpinBox(self.filePath)
        self.setting_space.setMinimum(0.5)
        self.setting_space.setMaximum(500.0)
        self.setting_space.setSingleStep(0.1)
        self.setting_space.setProperty("value", 1.0)
        self.setting_space.setObjectName("setting_space")
        self.verticalLayout_9.addWidget(self.setting_space)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.action_startDraw = QtWidgets.QPushButton(self.filePath)
        self.action_startDraw.setObjectName("action_startDraw")
        self.horizontalLayout_6.addWidget(self.action_startDraw)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.filePath)
        self.result = QtWidgets.QGroupBox(self.mainUI)
        self.result.setObjectName("result")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.result)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.o_Console = QtWidgets.QTextBrowser(self.result)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.o_Console.sizePolicy().hasHeightForWidth())
        self.o_Console.setSizePolicy(sizePolicy)
        self.o_Console.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.o_Console.setStyleSheet("QTextEdit { background-color:#1c101b; font-family:\'等距更纱黑体 T SC\',\'monospace\'; font-size:10pt; color: #128f16; white-space:pre}")
        self.o_Console.setFrameShape(QtWidgets.QFrame.Box)
        self.o_Console.setMidLineWidth(1)
        self.o_Console.setDocumentTitle("")
        self.o_Console.setUndoRedoEnabled(False)
        self.o_Console.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.o_Console.setOverwriteMode(False)
        self.o_Console.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.o_Console.setObjectName("o_Console")
        self.horizontalLayout_4.addWidget(self.o_Console)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.action_setClipboard = QtWidgets.QPushButton(self.result)
        self.action_setClipboard.setObjectName("action_setClipboard")
        self.verticalLayout_3.addWidget(self.action_setClipboard)
        self.gugugu = QtWidgets.QPushButton(self.result)
        self.gugugu.setObjectName("gugugu")
        self.verticalLayout_3.addWidget(self.gugugu)
        self.gugugugu = QtWidgets.QPushButton(self.result)
        self.gugugugu.setObjectName("gugugugu")
        self.verticalLayout_3.addWidget(self.gugugugu)
        self.action_cleanConsole = QtWidgets.QPushButton(self.result)
        self.action_cleanConsole.setObjectName("action_cleanConsole")
        self.verticalLayout_3.addWidget(self.action_cleanConsole)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.result)
        ttf2pcb.setCentralWidget(self.mainUI)
        self.menubar = QtWidgets.QMenuBar(ttf2pcb)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.func = QtWidgets.QMenu(self.menubar)
        self.func.setObjectName("func")
        self.ctrl = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.ctrl.setFont(font)
        self.ctrl.setObjectName("ctrl")
        self.about = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.file = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.file.setFont(font)
        self.file.setObjectName("file")
        ttf2pcb.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(ttf2pcb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        ttf2pcb.setStatusBar(self.statusBar)
        self.menu_demo = QtWidgets.QAction(ttf2pcb)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(9)
        self.menu_demo.setFont(font)
        self.menu_demo.setObjectName("menu_demo")
        self.gu = QtWidgets.QAction(ttf2pcb)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.gu.setFont(font)
        self.gu.setObjectName("gu")
        self.menu_loadstatus = QtWidgets.QAction(ttf2pcb)
        self.menu_loadstatus.setObjectName("menu_loadstatus")
        self.menu_exit = QtWidgets.QAction(ttf2pcb)
        self.menu_exit.setObjectName("menu_exit")
        self.func.addAction(self.menu_demo)
        self.func.addSeparator()
        self.func.addAction(self.gu)
        self.file.addAction(self.menu_loadstatus)
        self.file.addSeparator()
        self.file.addAction(self.menu_exit)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.func.menuAction())
        self.menubar.addAction(self.ctrl.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(ttf2pcb)
        QtCore.QMetaObject.connectSlotsByName(ttf2pcb)

    def retranslateUi(self, ttf2pcb):
        _translate = QtCore.QCoreApplication.translate
        ttf2pcb.setWindowTitle(_translate("ttf2pcb", "TTF字体绘制工具 V0.0.1alpha"))
        self.status.setTitle(_translate("ttf2pcb", "当前字体: (下版本可以给每个字符单独指定字体)"))
        self.o_fftFileName_current.setText(_translate("ttf2pcb", "(尚未选择字体)"))
        self.groupBox_3.setTitle(_translate("ttf2pcb", "选择字体(字体名称, 下版本可下拉选择系统字体)"))
        self.i_fontfileName.setPlaceholderText(_translate("ttf2pcb", "填写想要的字体文件路径"))
        self.action_cfmFontFile.setText(_translate("ttf2pcb", "确认"))
        self.filePath.setTitle(_translate("ttf2pcb", "参数设置"))
        self.label_9.setText(_translate("ttf2pcb", "附加参数: (嗯... 这一版本就这么意思一下吧, 下一版做成表格形式. 留空使用默认值)"))
        self.i_externSettings.setPlaceholderText(_translate("ttf2pcb", "这里可以指定每个字的工艺层和描边粗细(json的形式)"))
        self.label_4.setText(_translate("ttf2pcb", "需要绘制的文本: (纯文本. 本版本暂不支持富文本模式)"))
        self.i_sourceText.setPlaceholderText(_translate("ttf2pcb", "在这里输入要绘制的文本..."))
        self.label_3.setText(_translate("ttf2pcb", "绘制模式:"))
        self.setting_method.setCurrentText(_translate("ttf2pcb", "默认"))
        self.setting_method.setItemText(0, _translate("ttf2pcb", "默认"))
        self.setting_method.setItemText(1, _translate("ttf2pcb", "仅填充"))
        self.setting_method.setItemText(2, _translate("ttf2pcb", "仅描边"))
        self.setting_method.setItemText(3, _translate("ttf2pcb", "填充并描边"))
        self.label_5.setText(_translate("ttf2pcb", "字号缩放:"))
        self.setting_scale.setSuffix(_translate("ttf2pcb", "%"))
        self.label_6.setText(_translate("ttf2pcb", "采样间隔:"))
        self.setting_precision.setSuffix(_translate("ttf2pcb", "点"))
        self.label_7.setText(_translate("ttf2pcb", "字间距:"))
        self.setting_space.setSuffix(_translate("ttf2pcb", "%"))
        self.action_startDraw.setText(_translate("ttf2pcb", "开始绘制"))
        self.result.setTitle(_translate("ttf2pcb", "结果预览 (做不动了... 先用控制台信息占个地儿... 下版本可交互式修改结果的排版)"))
        self.o_Console.setHtml(_translate("ttf2pcb", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'等距更纱黑体 T SC\',\'monospace\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.action_setClipboard.setText(_translate("ttf2pcb", "写入剪贴板"))
        self.gugugu.setText(_translate("ttf2pcb", "还没做好"))
        self.gugugugu.setText(_translate("ttf2pcb", "咕咕咕"))
        self.action_cleanConsole.setText(_translate("ttf2pcb", "清空内容"))
        self.func.setTitle(_translate("ttf2pcb", "功能"))
        self.ctrl.setTitle(_translate("ttf2pcb", "选项"))
        self.about.setTitle(_translate("ttf2pcb", "帮助"))
        self.file.setTitle(_translate("ttf2pcb", "文件"))
        self.statusBar.setWhatsThis(_translate("ttf2pcb", "当前字体信息"))
        self.menu_demo.setText(_translate("ttf2pcb", "填入Demo"))
        self.menu_demo.setWhatsThis(_translate("ttf2pcb", "填写Demo和默认的参数以演示"))
        self.gu.setText(_translate("ttf2pcb", "下版再做吧..."))
        self.menu_loadstatus.setText(_translate("ttf2pcb", "恢复上次状态"))
        self.menu_exit.setText(_translate("ttf2pcb", "退出"))
